### ISSUE TITLE
Building subsections for crustal faults

### ISSUE THREAD

**Issue by thingbaijam** [opensha/opensha-core#14]
The subsections would generally have length shorter than 0.5 times the down-dip width (_DDW_), if  _maxSubSectionLen_ is defined 0.5 _DDW_. In turn, the combined length of 2 subsections would be shorter than _DDW_.  This implies that rupture length for considered smallest magnitude  (at least 2 subsections) would be shorter than rupture width (unless _AseismicSlipFactor_ is not zero).

When fault-dip is 90 degrees,  seismogenic thickness would be the same as _DDW_. It is then possible that the consideration: “requiring at least 2 subsections ensures that the minimum rupture lengths are approximately equal to the seismogenic thickness (Main report UCERF3, p27)” may not hold.  

On the other hand, what if we define the subsection length to be  at least 0.5 _DDW_ as follows: 

traceLength = faultTrace.getTraceLength();
dL = 0.5*_DDW_;
numSubSec = (int) traceLength/dL;
dF = (traceLength - (numSubSec*dL))/numSubSec;
sectionLength = dL+dF;

Would not this simply the procedure to build the subsections.

**Comment by kevinmilner** [comment]
I'm closing this as I'm archiving the old project. You can re-rase it in the opensha project if it's still an issue
